StudentWebControl/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using StudentControl.Model;
using StudentControl.Models;

namespace StudentWebControl.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student\
        StudentControlDBEntities db = new StudentControlDBEntities();

        public async Task<ActionResult> Index()
        {
            List<StudentControl.Models.Student> student = await (from t in db.Students
                                                                 select new StudentControl.Models.Student
                                                                 {
                                                                     Id = t.Id,
                                                                     Adress = t.Adress,
                                                                     DateOfBirth = t.BornDate,
                                                                     ClassId = t.ClassId,
                                                                     Image = t.Image,
                                                                     ParentName = t.ParentName,
                                                                     ParentSurname = t.ParentSurname,
                                                                     Phone = t.Phone,
                                                                     Telephone = t.Phone
                                                                 }).ToListAsync();
            return View(student);
        }

        public async Task<ActionResult> Creaate()
        {
            ViewData["Classes"] = new SelectList(await db.Classes.OrderBy(p => p.Name).ToArrayAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Creaate(UserStudent userStudent)
        {
            var usr = new User
            {
                Name = userStudent.user.Name,
                Password = userStudent.user.Password,
                EMail = userStudent.user.EMail,
                Surname = userStudent.user.Surname,
                Username = userStudent.user.Username,
                UserType = 1,
            };
            db.Users.Add(usr);
            await db.SaveChangesAsync();

            var std = new Student
            {
                Phone = userStudent.student.Phone,
                Adress = userStudent.student.Adress,
                BornDate = userStudent.student.DateOfBirth,
                ClassId = userStudent.student.ClassId,
                Id = usr.Id,
                ParentName = userStudent.student.ParentName,
                ParentSurname = userStudent.student.ParentSurname,
                Telephone = userStudent.student.Telephone,
            };
            db.Students.Add(std);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

StudentWebControl/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using StudentControl.Models;

namespace StudentWebControl.Controllers
{
    public class TeacherController : Controller
    {
        StudentControlDBEntities db = new StudentControlDBEntities();
        // GET: Teacher
        public async Task<ActionResult> Index()
        {
            return View(await db.Teachers.ToListAsync());
        }

        public async Task<ActionResult> Create()
        {
            ViewData["Classes"] = new SelectList(await db.Classes.OrderBy(p => p.Name).ToArrayAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(UserTeacher userTeacher)
        {
            var usr = new User
            {
                Name = userTeacher.user.Name,
                Password = userTeacher.user.Password,
                EMail = userTeacher.user.EMail,
                Surname = userTeacher.user.Surname,
                Username = userTeacher.user.Username,
                UserType = 1,
            };
            db.Users.Add(usr);

            var tch = new Teacher
            {
               Branch = userTeacher.teacher.Brahch,
               ClassId = userTeacher.teacher.ClassId,
               Id = usr.Id,
               Telephone = userTeacher.teacher.Telephone,
            };
            db.Teachers.Add(tch);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

StudentWebControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="PagaSoft" content="">
    <title>Başak Koleji yönetim paneli</title>
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="index.html">Başak Koleji</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="@Url.Action("Index","Home")">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Ana Sayfa</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="@Url.Action("Index","Student")">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Öğrenciler</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="@Url.Action("Index","Teacher")">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Hocalar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="@Url.Action("Index","Home")">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Sınıflar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="index.html">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Etkinlikler</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="index.html">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Ödevler</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="index.html">
                        <i class="fa fa-fw fa-home"></i>
                        <span class="nav-link-text">Bildirimler</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out"></i>Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Tüm haklar Pars Organizasyona aittir © 2017</small>
            </div>
        </div>
    </footer>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/popper/popper.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script src="~/vendor/chart.js/Chart.min.js"></script>
    <script src="~/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin.min.js"></script>
    <!-- Custom scripts for this page-->
    <script src="~/js/sb-admin-datatables.min.js"></script>
    <script src="~/js/sb-admin-charts.min.js"></script>
</body>

</html>